# netlify.toml — monorepo-friendly

[build]
# run the build from the REPO ROOT, but execute npm *inside* the subfolder
command = "npm ci --prefix 46bettor-frontend && npm run build --prefix 46bettor-frontend"
publish = "46bettor-frontend/dist"

[build.environment]
# Netlify supports 18/20 LTS. Use 20 to match modern Vite.
NODE_VERSION = "20"
VITE_API_BASE = "https://api.46bettor.com"

# Single Page App fallback (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
