# netlify.toml — build the React app in /46bettor-frontend

[build]
# Use the subfolder as the working dir for the build
base    = "46bettor-frontend"
publish = "dist"
# Use npm install (not ci) so it works even if package-lock.json isn't committed
command = "npm install && npm run build"

[build.environment]
NODE_VERSION = "20"
VITE_API_BASE = "https://api.46bettor.com"

# SPA fallback for React Router
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
